sudo: false

addons:
    apt:
      packages:
       - unzip
       - make
       - cmake-data
       - cmake
       - libglu1-mesa-dev
       - libgl1-mesa-dev 

matrix:
    include:
    - os: linux
      language: c++
      install: true
    - os: osx
      language: c++
      osx_image: xcode9.4
      install: true

#cache:
  #ccache: true
  #directories:
   #- $HOME/Library/Caches/Homebrew
   # TODO: how can we do conditional caching of directories (depending on OS)
   #- /home/travis/build/miho/OCC-CSG/oce-OCE-0.18.3
   #- /Users/travis/build/miho/OCC-CSG/oce-OCE-0.18.3 

env:
  global:
    - OCC_VERSION="v7.2.0.1"
    #- OCC_VERSION="v7.3.0.2"
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PATH=/usr/lib/ccache:${PATH}; fi
    - TIMEOUT_BUILD='30m'
    - BUILD_SUCCESS=true
    
before_install:
  # installing ccache and freetype packages via homebrew
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ccache; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  # adding timeout command to path for os x
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PATH="$PATH:/usr/local/opt/coreutils/libexec/gnubin"; fi
  
script: 
    - export OUR_DIR=$(pwd)
    - echo "home directory $OUR_DIR"
    
    # downloading occ
    - mkdir -p dependencies
    - cd dependencies
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then curl https://github.com/miho/occ-for-occ-csg/releases/download/$OCC_VERSION/opencascade-$OCC_VERSION-linux-x64.zip -LO ; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then unzip opencascade-$OCC_VERSION-linux-x64.zip > /dev/null ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then curl https://github.com/miho/occ-for-occ-csg/releases/download/$OCC_VERSION/opencascade-$OCC_VERSION-macos.zip -LO ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then unzip opencascade-$OCC_VERSION-macos.zip > /dev/null ; fi
    
    - cd $OUR_DIR
    
    # setting OCC install dir
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OCC_INSTALL_DIR=$OUR_DIR/dependencies/opencascade-$OCC_VERSION-macos/lib/cmake/opencascade; mv $OUR_DIR/dependencies/opencascade-$OCC_VERSION-macos/lib/libfreetype.a.6 $OUR_DIR/dependencies/opencascade-$OCC_VERSION-macos/lib/libfreetype.a ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export OCC_INSTALL_DIR=$OUR_DIR/dependencies/opencascade-$OCC_VERSION-linux-x64/lib/cmake/opencascade; mv $OUR_DIR/dependencies/opencascade-$OCC_VERSION-linux-x64/lib/libfreetype.a.6 $OUR_DIR/dependencies/opencascade-$OCC_VERSION-linux-x64/lib/libfreetype.a ; fi
    
    
    # finally build and test occ-csg
    - cd $OUR_DIR
    - mkdir -p build && cd build
    - (! $BUILD_SUCCESS && echo ">> skipping build until ccache and compilation of oce works. restart task or schedule new task.") || cmake .. -DOpenCASCADE_DIR=$OCC_INSTALL_DIR
    - (! $BUILD_SUCCESS && echo ">> skipping build until ccache and compilation of oce works. restart task or schedule new task.") || make && bin/occ-csg --help       

before_deploy:
    - cd $OUR_DIR
    - mkdir release && cd release
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir -p occ-csg-$TRAVIS_TAG-macos/bin; cp $OUR_DIR/build/bin/occ-csg occ-csg-$TRAVIS_TAG-macos/bin; cp $OUR_DIR/README.md occ-csg-$TRAVIS_TAG-macos/; cp $OUR_DIR/THIRDPARTY-LICENSES occ-csg-$TRAVIS_TAG-macos/; cp $OUR_DIR/LICENSE occ-csg-$TRAVIS_TAG-macos/ ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then zip -r occ-csg-$TRAVIS_TAG-macos.zip occ-csg-$TRAVIS_TAG-macos/; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir -p occ-csg-$TRAVIS_TAG-linux-x64/bin; cp $OUR_DIR/build/bin/occ-csg occ-csg-$TRAVIS_TAG-linux-x64/bin; cp $OUR_DIR/README.md occ-csg-$TRAVIS_TAG-linux-x64/; cp $OUR_DIR/THIRDPARTY-LICENSES occ-csg-$TRAVIS_TAG-linux-x64/; cp $OUR_DIR/LICENSE occ-csg-$TRAVIS_TAG-linux-x64/ ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then zip -r occ-csg-$TRAVIS_TAG-linux-x64.zip occ-csg-$TRAVIS_TAG-linux-x64/; fi   

deploy:
    - provider: releases
    
      api_key:
        secure: zjSgPQIowqYPUILskt3+Bn1+wfvJsIQz4INZbusPRMCJvLchQzIxvejURPqb7f067cDbHXFoUjGydgHz6WdIFhp31scML5816enBTQeVOgKwc3cLlV2FY9i/ymxckF7fnJ0DTyz6f99bGx8oQSglNfiyOt8JO6pYzB7ZpEQaGByqyYiBsXGjAEauezbux1jNPo5B8yt4cwfy/uH9RvCpNMXgbJSFqm87nfrovAbzVda6hjLPWeY7AmP3aO9Vv0YL7nYXrbyYLYkyO/lKz87jVCvxWW03rDo+5oAfCcZJAQ/4+Mhek6YeiqWC+kg7V35xRlbt6l5VJnB1UFQTnNXbvPps7EM0c0/0O4mBcMegIojdvApNV4U960ssa4e2jekhP6TsLBuPgwasoh7lYFWcX5IqtEbtJAKTBIO7ghPnSbLQmcrx57cTghFX8lJJVJsYSWOzKs5FZv3XdtKqK6fwqR3icjwTkuVuiTCn1/uXu8KCnTyyMhXKaLMZw0a5dP9MH4ZRNmFD8X5i9ZdLdV0e9T05GHSj7vNy9+dNi6AGX0j18LSrlnw9FDCkRk2YtWA5T/oSoJ8WEYa/i/2S30propGJt2xtN+2qW8QBq23zquNleh1VZwy31imXPlTx3r5ZQWNKE3hBWLnmoY87qkaIk0jZqX6bWw+KUleNT7lfIfk=
      
      skip_cleanup: true
    
      file: $OUR_DIR/release/occ-csg-$TRAVIS_TAG-linux-x64.zip
    
      on:
        condition: $TRAVIS_OS_NAME = linux
        tags: true
        #repo: miho/OCC-CSG
        
    - provider: releases
    
      api_key:
        secure: zjSgPQIowqYPUILskt3+Bn1+wfvJsIQz4INZbusPRMCJvLchQzIxvejURPqb7f067cDbHXFoUjGydgHz6WdIFhp31scML5816enBTQeVOgKwc3cLlV2FY9i/ymxckF7fnJ0DTyz6f99bGx8oQSglNfiyOt8JO6pYzB7ZpEQaGByqyYiBsXGjAEauezbux1jNPo5B8yt4cwfy/uH9RvCpNMXgbJSFqm87nfrovAbzVda6hjLPWeY7AmP3aO9Vv0YL7nYXrbyYLYkyO/lKz87jVCvxWW03rDo+5oAfCcZJAQ/4+Mhek6YeiqWC+kg7V35xRlbt6l5VJnB1UFQTnNXbvPps7EM0c0/0O4mBcMegIojdvApNV4U960ssa4e2jekhP6TsLBuPgwasoh7lYFWcX5IqtEbtJAKTBIO7ghPnSbLQmcrx57cTghFX8lJJVJsYSWOzKs5FZv3XdtKqK6fwqR3icjwTkuVuiTCn1/uXu8KCnTyyMhXKaLMZw0a5dP9MH4ZRNmFD8X5i9ZdLdV0e9T05GHSj7vNy9+dNi6AGX0j18LSrlnw9FDCkRk2YtWA5T/oSoJ8WEYa/i/2S30propGJt2xtN+2qW8QBq23zquNleh1VZwy31imXPlTx3r5ZQWNKE3hBWLnmoY87qkaIk0jZqX6bWw+KUleNT7lfIfk=
      
      skip_cleanup: true
    
      file: $OUR_DIR/release/occ-csg-$TRAVIS_TAG-macos.zip
    
      on:
        condition: $TRAVIS_OS_NAME = osx
        tags: true
        #repo: miho/OCC-CSG      
